// <auto-generated />
using System;
using Cinema_Booking_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MovieTheater.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251010122524_screenDeleteTest")]
    partial class screenDeleteTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Cinema_Booking_System.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("actor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            Name = "John Carter",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 2,
                            Age = 29,
                            Name = "Emma Johnson",
                            Nationality = "British"
                        },
                        new
                        {
                            Id = 3,
                            Age = 41,
                            Name = "Kenji Tanaka",
                            Nationality = "Japanese"
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            Name = "Sophia Rossi",
                            Nationality = "Italian"
                        });
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("ScreenId")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ScreenId");

                    b.ToTable("booking");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ScreenId = 1,
                            SeatNumber = 15,
                            Status = "Confirmed"
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2025, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            ScreenId = 2,
                            SeatNumber = 42,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            BookingDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            ScreenId = 3,
                            SeatNumber = 7,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "adel@example.com",
                            Name = "Adel Mostafa",
                            Phone = "+201234567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mona@example.com",
                            Name = "Mona Youssef",
                            Phone = "+201109876543"
                        });
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("customerProfile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Nile Street, Cairo",
                            CustomerId = 1,
                            DateOfBirth = new DateTime(2005, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Tahrir Square, Giza",
                            CustomerId = 2,
                            DateOfBirth = new DateTime(1998, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "An epic tale of courage and loyalty.",
                            Duration = 145,
                            Rating = 8.7m,
                            ReleaseDate = new DateTime(2022, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Kingdom"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A sci-fi journey beyond imagination.",
                            Duration = 132,
                            Rating = 9.1m,
                            ReleaseDate = new DateTime(2023, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Galactic Odyssey"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A thrilling mystery in a quiet town.",
                            Duration = 118,
                            Rating = 7.9m,
                            ReleaseDate = new DateTime(2021, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Silent Whispers"
                        });
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ScreenNumber")
                        .IsUnique();

                    b.ToTable("screen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 120,
                            MovieId = 1,
                            ScreenNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 80,
                            MovieId = 2,
                            ScreenNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 150,
                            MovieId = 1,
                            ScreenNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 100,
                            MovieId = 3,
                            ScreenNumber = 4
                        });
                });

            modelBuilder.Entity("Project.Models.MovieActor", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("movieActor");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 2
                        },
                        new
                        {
                            ActorId = 1,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 3
                        });
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Booking", b =>
                {
                    b.HasOne("Cinema_Booking_System.Models.Customer", "customer")
                        .WithMany("bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cinema_Booking_System.Models.Screen", "screen")
                        .WithMany("bookings")
                        .HasForeignKey("ScreenId");

                    b.Navigation("customer");

                    b.Navigation("screen");
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.CustomerProfile", b =>
                {
                    b.HasOne("Cinema_Booking_System.Models.Customer", "customer")
                        .WithOne("customerProfile")
                        .HasForeignKey("Cinema_Booking_System.Models.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Screen", b =>
                {
                    b.HasOne("Cinema_Booking_System.Models.Movie", "movie")
                        .WithMany("screens")
                        .HasForeignKey("MovieId");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("Project.Models.MovieActor", b =>
                {
                    b.HasOne("Cinema_Booking_System.Models.Actor", "actor")
                        .WithMany("movies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cinema_Booking_System.Models.Movie", "movie")
                        .WithMany("actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actor");

                    b.Navigation("movie");
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Actor", b =>
                {
                    b.Navigation("movies");
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Customer", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("customerProfile");
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Movie", b =>
                {
                    b.Navigation("actors");

                    b.Navigation("screens");
                });

            modelBuilder.Entity("Cinema_Booking_System.Models.Screen", b =>
                {
                    b.Navigation("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
